plugins {
    id 'com.android.application'
}

android {
    namespace 'com.eb.poker'
    compileSdk 34

    defaultConfig {
        applicationId "com.eb.poker"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "2.0"
    }

    signingConfigs {
        release {
            // TODO: Fill in your keystore details
            storeFile file("../my-release-key.keystore")
            storePassword System.getenv('KEYSTORE_STORE_PASSWORD') ?: project.findProperty('KEYSTORE_STORE_PASSWORD') ?: ""
            keyAlias System.getenv('KEYSTORE_KEY_ALIAS') ?: project.findProperty('KEYSTORE_KEY_ALIAS') ?: ""
            keyPassword System.getenv('KEYSTORE_KEY_PASSWORD') ?: project.findProperty('KEYSTORE_KEY_PASSWORD') ?: ""
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.9.0'
}
